### ISSUE TITLE
loopback-graphql-server authentication problems

### ISSUE THREAD

**Issue by rajnarayan** [yahoohung/loopback-graphql-server#7]
We have been using your loopback-graphql-server package for our project for a few months now and its been working really well for us. Thank you very help for doing this.

I have have recently run into a problem while trying to enable authentication that I'm hoping you can help shed some light on. I've tried passing the access token in the header as well as a query parameter, but loopback seems to not get the right accessContext. 

Is there something i need to enable while running the graphql server for auth to work?

HEADER: authorization: e58f7043-573c-4e98-aa90-**********
QUERY: http://localhost:3000/graphql?accessToken=e58f7043-573c-4e98-aa90-*********

LOGS

  loopback:security:role isInRole(): $unauthenticated +2m
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: [] +0ms
  loopback:security:access-context modelName Pipeline +0ms
  loopback:security:access-context modelId undefined +0ms
  loopback:security:access-context property find +0ms
  loopback:security:access-context method find +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "$anonymous" +1ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() null +0ms
  loopback:security:access-context isAuthenticated() false +0ms
  loopback:security:role Custom resolver found for role $unauthenticated +0ms
  loopback:security:acl The following ACLs were searched:  +0ms
  loopback:security:acl ---ACL--- +0ms
  loopback:security:acl model Pipeline +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId $unauthenticated +0ms
  loopback:security:acl accessType WRITE +0ms
  loopback:security:acl permission DENY +0ms
  loopback:security:acl with score: -1 +0ms
  loopback:security:acl ---Resolved--- +0ms
  loopback:security:access-context ---AccessRequest--- +0ms
  loopback:security:access-context  model Pipeline +0ms
  loopback:security:access-context  property find +0ms
  loopback:security:access-context  accessType READ +0ms
  loopback:security:access-context  permission ALLOW +0ms
  loopback:security:access-context  isWildcard() false +1ms
  loopback:security:access-context  isAllowed() true +0ms

**Comment by yahoohung** [comment]
Hi, Raj. Could you please test the same query on  (http://localhost:3000/graphiql?access_token=xxx). It is possible to access resources by pass the access token into header with Authorization or on query with access_token.
