### ISSUE TITLE
How retrieve real document id from graphql response

### ISSUE THREAD

**Issue by kuksik** [yahoohung/loopback-graphql-server#9]
I have project based on loopback all data stored in the "gcloud datastore".
In general everything work fine. But I have one misunderstanding. How I can retrive real document id from graphql response.

I have one idea. I can add field customId to the model and use it for request. But I want to know what is the best practice for this case?

**Comment by gerswin** [comment]
import {Buffer} from 'buffer'

export default function fromGlobalId(globalId) {
    const unbasedGlobalId = Buffer.from(globalId, "base64").toString("utf8");
    const delimiterPos = unbasedGlobalId.indexOf(":");
    return {type: unbasedGlobalId.substring(0, delimiterPos), id: unbasedGlobalId.substring(delimiterPos + 1)};
}

**Comment by kuksik** [comment]
@gerswin thank you!
